### PR TITLE
Refacture sentence to ipa

### PR DESCRIPTION
**Pull request by jasminsternkopf**
pls check

### CODE REVIEW

**Comment by jasminsternkopf** [comment]
Please check
should the majority of tests in CMUDict.tests.py be deleted?

**Comment by stefantaubert** [comment]
- please resolve merge conficts
- please format files
- please try to simplify recombine_words with join
- please try to simplify for-loop in sentence_to_ipa() in SentenceToIPA
- please keep tests of cmudict
- please rename import of sentence_to_ipa in cmudict
- please create own constant for -> char in string.punctuation or char == "\n"
- please add return-type to find_combination_of_certain_length_in_dict and word_with_apo
- please correct return-type of get_ipa_of_words_with_hyphen or add assert ipa is not None
- please add assertEqual len==4 to test_word_with_apo__apo_at_beginning__returns_word_with_apo_at_beginning__empty_string__word_with_one_more_apo_at_beginning__and_word_with_apo_at_end

**Comment by jasminsternkopf** [comment]
formating done

**Comment by stefantaubert** [comment]
please fix typo PUNCTUATONS_AND_LINEBREAK

**Pull request merged**
